"""Fake backends — deterministic in-memory/file-based backends for testing.

These are **public utilities**. Use them in your own pipeline tests to avoid
network calls and get deterministic, inspectable results::

    from canon.backends import FakeLLMBackend, FakeImageBackend, FakeMusicBackend, FakeSFXBackend

    fake_img = FakeImageBackend()
    result = fake_img.generate_and_save("a red dragon", "/tmp/test.png", 256, 256)
    assert result is True
    assert len(fake_img.calls) == 1

``FakeChatBackend`` (Phase 1 A1) is the scripted twin of the agent's chat
backends — the $0 leg the eval runner and every loop test run on.
"""

from __future__ import annotations

import io
import json
import time
from collections.abc import Callable, Iterator
from pathlib import Path

from canon.llm.chat import (
    ChatEvent,
    ChatRequest,
    ContentBlockDone,
    MessageStart,
    MessageStop,
    TextDelta,
    ThinkingDelta,
    ToolInputDelta,
    ToolUseStart,
    Usage,
)
from canon.llm.request import LLMRequest

# ---------------------------------------------------------------------------
# Minimal placeholder bytes
# ---------------------------------------------------------------------------

# Minimal valid 1×1 transparent PNG (70 bytes), generated by PIL itself.
# The previous hand-rolled bytes had a truncated IDAT stream: PIL's lazy
# Image.open() accepted the header, but any full decode (convert, load)
# raised "broken data stream" — verified now by a round-trip DECODE, not
# just open (tests/test_backends_fake.py guards it).
_MIN_PNG_BYTES = bytes.fromhex(
    "89504e470d0a1a0a"              # PNG signature
    "0000000d49484452"              # IHDR chunk length + type
    "00000001"                      # width: 1
    "00000001"                      # height: 1
    "08060000001f15c489"            # bit depth 8, RGBA, CRC
    "0000000d49444154"              # IDAT chunk length + type
    "789c6360606060000000050001"    # zlib-compressed 1×1 transparent pixel
    "a5f64540"                      # CRC
    "0000000049454e44ae426082"      # IEND
)

# Minimal *valid silent* MP3 — a run of MPEG-1 Layer III frames (128kbps,
# 44.1kHz, ~0.42s total) carrying zeroed audio data, capped with an ID3v1
# trailer so decoders stop cleanly at end-of-stream instead of resyncing into
# zeros.  Loads WITHOUT warnings through both pygame.mixer.Sound and
# pygame.mixer.music.load (verified against pygame 2.6 / SDL_mixer 2.28).
#
# This is a *placeholder*: fake-asset runs write silent audio so the data tree
# is complete and loads cleanly, but no real audio is generated.  Consumers
# detect placeholder assets via the "fake" backend names recorded in
# generation_stats.json / manifest.json — see GenerationStats.
_SILENT_MP3_FRAME = b"\xff\xfb\x90\x00" + b"\x00" * 413  # one 417-byte L3 frame
_MIN_MP3_BYTES = _SILENT_MP3_FRAME * 16 + b"TAG" + b"\x00" * 125


# ---------------------------------------------------------------------------
# FakeLLMBackend
# ---------------------------------------------------------------------------


class FakeLLMBackend:
    """Deterministic in-memory LLM backend for testing.

    Public utility — use this in your own pipeline tests to avoid network
    calls. Records every request to ``.calls`` for assertions.

    Three modes:

    **List mode** — provide a list of strings. Responses are returned in
    order. ``IndexError`` is raised if the list is exhausted before all
    requests are served::

        fake = FakeLLMBackend(["first", "second"])

    **Dict mode** — provide a ``{substring: response}`` mapping. The
    ``user_message`` of each request is checked against every key; the first
    matching value is returned. ``KeyError`` is raised if no key matches::

        fake = FakeLLMBackend({"dragon": "Here be dragons.", "sword": "A fine blade."})

    **Callable mode** — provide a function ``(LLMRequest) -> str``. The
    function is called with the full request and its return value is used::

        fake = FakeLLMBackend(lambda req: f"echo: {req.user_message[:20]}")

    Attributes:
        calls: All ``LLMRequest`` objects passed to ``generate()``, in call
            order. Inspect this in assertions to verify the client sent the
            expected prompts.
    """

    def __init__(
        self,
        responses: list[str] | dict[str, str] | Callable[[LLMRequest], str],
    ) -> None:
        self._responses = responses
        self._index = 0
        self.calls: list[LLMRequest] = []

    def generate(self, request: LLMRequest) -> str:
        """Return the next canned response and record the request.

        Args:
            request: The ``LLMRequest`` from the caller.

        Returns:
            The configured response string.

        Raises:
            IndexError: (list mode) if all responses have been consumed.
            KeyError: (dict mode) if no key matches ``request.user_message``.
            TypeError: if ``responses`` was constructed with an unsupported type.
        """
        self.calls.append(request)

        # Callable mode — check this first so a callable isn't accidentally
        # matched by the isinstance checks below (lambdas are callable and are
        # neither list nor dict, but a subclass of list could theoretically be
        # callable too — checking callable last on list/dict would be ambiguous).
        if callable(self._responses) and not isinstance(self._responses, (list, dict)):
            return self._responses(request)

        if isinstance(self._responses, list):
            response = self._responses[self._index]
            self._index += 1
            return response

        if isinstance(self._responses, dict):
            for key, value in self._responses.items():
                if key in request.user_message:
                    return value
            raise KeyError(
                f"FakeLLMBackend: no dict key matched user_message: "
                f"{request.user_message[:80]}..."
            )

        raise TypeError(
            f"FakeLLMBackend: unsupported responses type {type(self._responses)}"
        )


# ---------------------------------------------------------------------------
# FakeVLMBackend
# ---------------------------------------------------------------------------


class FakeVLMBackend:
    """Deterministic vision-judge backend for testing.

    Mirrors ``FakeLLMBackend``'s callable mode: the responder receives
    ``(prompt, images)`` and returns the verdict string, so callers supply
    canned verdicts keyed off prompt markers. Records every call to
    ``.calls`` (images stored by byte length only — keeping full PNGs per
    call would bloat assertions for no diagnostic gain).

    Public utility — downstream users testing VLM QA loops without paying
    for vision-model calls::

        fake = FakeVLMBackend(lambda prompt, images: '{"passed": true}')
    """

    #: Identity folded into reports/provenance, like real backends' model.
    model = "fake-vlm"

    def __init__(self, responder: Callable[[str, list[bytes]], str]) -> None:
        self._responder = responder
        self.calls: list[dict] = []

    def judge(self, prompt: str, images: list[bytes], max_tokens: int = 1024) -> str:
        """Return the responder's canned verdict and record the call."""
        self.calls.append(
            {
                "prompt": prompt,
                "image_sizes": [len(data) for data in images],
                "max_tokens": max_tokens,
            }
        )
        return self._responder(prompt, images)


# ---------------------------------------------------------------------------
# FakeImageBackend
# ---------------------------------------------------------------------------


class FakeImageBackend:
    """Deterministic image backend for tests.

    Copies a placeholder PNG from ``asset_dir`` to the requested save path.
    Records every call to ``.calls`` for assertion.

    Public utility — downstream users testing canon pipelines without
    paying for fal.ai calls.

    Args:
        asset_dir: Directory containing one or more PNG files.
        placeholder: Specific PNG path; takes precedence over ``asset_dir``.

    If neither is provided, a minimal 1×1 transparent PNG is generated inline.
    """

    #: The fake-transparency gate (platformer pack ``tileset_art``)
    #: passes trusted-alpha backends through untouched: placeholder
    #: bytes are not generated art, and the fake twins' $0 runs must
    #: stay byte-identical with identical call counts.
    trusted_alpha = True

    def __init__(
        self,
        asset_dir: str | Path | None = None,
        placeholder: str | Path | None = None,
        capabilities: frozenset[str] | set[str] | None = None,
    ) -> None:
        self.asset_dir = Path(asset_dir) if asset_dir else None
        self.placeholder = Path(placeholder) if placeholder else None
        self.calls: list[dict] = []
        # Declarable per test (graphics arc): lets $0 tests exercise
        # capability degradation (a fake claiming native_pixels skips
        # grid-snap; one without animation_sheets forces the static
        # fallback). None = the derived default set.
        if capabilities is not None:
            self.capabilities = frozenset(capabilities)

    def generate(self, prompt: str, width: int, height: int) -> bytes:
        """Return placeholder PNG bytes and record the call."""
        self.calls.append({"prompt": prompt, "width": width, "height": height})
        return self._placeholder_bytes()

    async def generate_async(self, prompt: str, width: int, height: int) -> bytes:
        """Async variant of ``generate``."""
        return self.generate(prompt, width, height)

    def generate_and_save(
        self, prompt: str, filepath: str, width: int, height: int
    ) -> bool:
        """Write placeholder PNG to ``filepath`` and record the call."""
        self.calls.append(
            {"prompt": prompt, "filepath": filepath, "width": width, "height": height}
        )
        dest = Path(filepath)
        dest.parent.mkdir(parents=True, exist_ok=True)
        dest.write_bytes(self._placeholder_bytes())
        return True

    async def generate_and_save_async(
        self, prompt: str, filepath: str, width: int, height: int
    ) -> bool:
        """Async variant of ``generate_and_save``."""
        return self.generate_and_save(prompt, filepath, width, height)

    # -- img2img (implements ``ImageEditBackend``) --------------------------

    def edit(
        self,
        image_bytes: bytes,
        prompt: str,
        width: int,
        height: int,
        references: list[bytes] | None = None,
    ) -> bytes:
        """Return a deterministic canned multi-frame sprite SHEET and record
        the call. The sheet holds ``_EDIT_SHEET_FRAMES`` opaque blobs on a
        white field, evenly spaced with clear gaps, so content-aware frame
        segmentation recovers exactly that many frames — the animation slicing
        path runs at $0. ``references`` are RECORDED (count) but do not change
        the output, so fake runs stay byte-identical. Byte-identical for
        identical ``(width, height)``."""
        self.calls.append(
            {
                "op": "edit",
                "prompt": prompt,
                "width": width,
                "height": height,
                "image_bytes": len(image_bytes),
                "references": len(references or []),
            }
        )
        return self._edit_sheet_bytes(width, height)

    async def edit_async(
        self,
        image_bytes: bytes,
        prompt: str,
        width: int,
        height: int,
        references: list[bytes] | None = None,
    ) -> bytes:
        """Async variant of ``edit``."""
        return self.edit(image_bytes, prompt, width, height, references)

    #: Frame count the canned edit sheet draws — a fixed, evenly-spaced count
    #: so segmentation is deterministic. Real img2img ignores exact counts;
    #: the animation phase records whatever it segments, not this number.
    _EDIT_SHEET_FRAMES = 4

    @classmethod
    def _edit_sheet_bytes(cls, width: int, height: int) -> bytes:
        """Deterministic white-background sheet of evenly-spaced opaque blobs.
        Falls back to the 1×1 stub only if Pillow is somehow absent (the pack
        always installs it; the animation path needs it regardless)."""
        try:
            from PIL import Image, ImageDraw
        except ImportError:  # pragma: no cover — pack installs Pillow
            return _MIN_PNG_BYTES
        w, h = max(cls._EDIT_SHEET_FRAMES, width), max(4, height)
        img = Image.new("RGBA", (w, h), (255, 255, 255, 255))
        draw = ImageDraw.Draw(img)
        cell = w // cls._EDIT_SHEET_FRAMES
        radius = max(2, min(cell, h) // 3)
        cy = h // 2
        for i in range(cls._EDIT_SHEET_FRAMES):
            cx = i * cell + cell // 2
            draw.ellipse(
                [cx - radius, cy - radius, cx + radius, cy + radius],
                fill=(60, 90, 200, 255),
            )
            # a per-frame "leg" nub so slices differ yet stay deterministic
            leg = radius + (i % 3)
            draw.rectangle([cx - 2, cy, cx + 2, cy + leg], fill=(60, 90, 200, 255))
        buf = io.BytesIO()
        img.save(buf, format="PNG")
        return buf.getvalue()

    def _placeholder_bytes(self) -> bytes:
        if self.placeholder and self.placeholder.exists():
            return self.placeholder.read_bytes()
        if self.asset_dir and self.asset_dir.exists():
            pngs = list(self.asset_dir.glob("*.png"))
            if pngs:
                return pngs[0].read_bytes()
        return _MIN_PNG_BYTES


# ---------------------------------------------------------------------------
# FakeMusicBackend
# ---------------------------------------------------------------------------


class FakeMusicBackend:
    """Deterministic music backend for tests.

    Copies a placeholder MP3 from ``asset_dir`` to the requested save path.
    Records every call to ``.calls`` for assertion.

    Public utility — downstream users testing canon pipelines without
    paying for Lyria/Suno API calls.

    Args:
        asset_dir: Directory containing one or more MP3 files.
        placeholder: Specific MP3 path; takes precedence over ``asset_dir``.

    If neither is provided, a minimal silent MP3 stub is generated inline.
    """

    def __init__(
        self,
        asset_dir: str | Path | None = None,
        placeholder: str | Path | None = None,
    ) -> None:
        self.asset_dir = Path(asset_dir) if asset_dir else None
        self.placeholder = Path(placeholder) if placeholder else None
        self.calls: list[dict] = []

    def generate(self, prompt: str, duration_seconds: int) -> bytes:
        """Return placeholder MP3 bytes and record the call."""
        self.calls.append({"prompt": prompt, "duration_seconds": duration_seconds})
        return self._placeholder_bytes()

    async def generate_async(self, prompt: str, duration_seconds: int) -> bytes:
        """Async variant of ``generate``."""
        return self.generate(prompt, duration_seconds)

    def generate_and_save(
        self, prompt: str, filepath: str, duration_seconds: int
    ) -> bool:
        """Write placeholder MP3 to ``filepath`` and record the call."""
        self.calls.append(
            {"prompt": prompt, "filepath": filepath, "duration_seconds": duration_seconds}
        )
        dest = Path(filepath)
        dest.parent.mkdir(parents=True, exist_ok=True)
        dest.write_bytes(self._placeholder_bytes())
        return True

    async def generate_and_save_async(
        self, prompt: str, filepath: str, duration_seconds: int
    ) -> bool:
        """Async variant of ``generate_and_save``."""
        return self.generate_and_save(prompt, filepath, duration_seconds)

    def _placeholder_bytes(self) -> bytes:
        if self.placeholder and self.placeholder.exists():
            return self.placeholder.read_bytes()
        if self.asset_dir and self.asset_dir.exists():
            mp3s = list(self.asset_dir.glob("*.mp3"))
            if mp3s:
                return mp3s[0].read_bytes()
        return _MIN_MP3_BYTES


# ---------------------------------------------------------------------------
# FakeSFXBackend
# ---------------------------------------------------------------------------


class FakeSFXBackend:
    """Deterministic SFX backend for tests.

    Copies a placeholder MP3 from ``asset_dir`` to the requested save path.
    Records every call to ``.calls`` for assertion.

    Public utility — downstream users testing canon pipelines without
    paying for ElevenLabs API calls.

    Args:
        asset_dir: Directory containing one or more MP3 files.
        placeholder: Specific MP3 path; takes precedence over ``asset_dir``.

    If neither is provided, a minimal silent MP3 stub is generated inline.
    """

    def __init__(
        self,
        asset_dir: str | Path | None = None,
        placeholder: str | Path | None = None,
    ) -> None:
        self.asset_dir = Path(asset_dir) if asset_dir else None
        self.placeholder = Path(placeholder) if placeholder else None
        self.calls: list[dict] = []

    def generate(self, prompt: str, duration_seconds: float, loop: bool) -> bytes:
        """Return placeholder MP3 bytes and record the call."""
        self.calls.append(
            {"prompt": prompt, "duration_seconds": duration_seconds, "loop": loop}
        )
        return self._placeholder_bytes()

    async def generate_async(
        self, prompt: str, duration_seconds: float, loop: bool
    ) -> bytes:
        """Async variant of ``generate``."""
        return self.generate(prompt, duration_seconds, loop)

    def generate_and_save(
        self, prompt: str, filepath: str, duration_seconds: float, loop: bool
    ) -> bool:
        """Write placeholder MP3 to ``filepath`` and record the call."""
        self.calls.append(
            {
                "prompt": prompt,
                "filepath": filepath,
                "duration_seconds": duration_seconds,
                "loop": loop,
            }
        )
        dest = Path(filepath)
        dest.parent.mkdir(parents=True, exist_ok=True)
        dest.write_bytes(self._placeholder_bytes())
        return True

    async def generate_and_save_async(
        self, prompt: str, filepath: str, duration_seconds: float, loop: bool
    ) -> bool:
        """Async variant of ``generate_and_save``."""
        return self.generate_and_save(prompt, filepath, duration_seconds, loop)

    def _placeholder_bytes(self) -> bytes:
        if self.placeholder and self.placeholder.exists():
            return self.placeholder.read_bytes()
        if self.asset_dir and self.asset_dir.exists():
            mp3s = list(self.asset_dir.glob("*.mp3"))
            if mp3s:
                return mp3s[0].read_bytes()
        return _MIN_MP3_BYTES


# ---------------------------------------------------------------------------
# FakeChatBackend
# ---------------------------------------------------------------------------


class FakeChatBackend:
    """Deterministic scripted chat backend for testing (Phase 1 A1).

    Implements ``canon.backends.base.ChatBackend`` the way ``FakeLLMBackend``
    implements ``LLMBackend``: canned assistant turns, consumed in order,
    every request recorded to ``.calls``. It streams the exact event order
    the Protocol documents so loop code exercised against it is exercised
    against the real contract — text arrives in at least two deltas, tool
    inputs arrive as a JSON delta, every block gets a ``ContentBlockDone``,
    and ``MessageStop`` carries the final content with ids filled in.

    Two modes:

    **List mode** — a list of turns played in order; ``IndexError`` once the
    script is exhausted. A turn is either a list of canonical assistant
    blocks (``stop_reason`` inferred: ``tool_use`` when any block is a
    tool_use, else ``end_turn``) or a dict ``{"content": [...],
    "stop_reason": "...", "stop_details": {...}}`` to script a refusal,
    ``max_tokens``, etc.::

        fake = FakeChatBackend([
            [{"type": "tool_use", "name": "validate_level", "input": {"level_id": "l6"}}],
            [{"type": "text", "text": "The exit is unreachable."}],
        ])

    **Callable mode** — ``(ChatRequest) -> turn`` for scripts that branch on
    the history.

    Tool-use blocks without an ``id`` get ``toolu_fake_<n>`` (``n`` counts
    per backend instance). Usage on every turn is ``Usage()`` — zeros,
    honestly: nothing was measured, and this backend is the $0 leg. No
    randomness anywhere.

    **Pacing (row P1-A7).** ``delay_s`` sleeps that long between the events
    a turn yields, and ``pace`` is called with each event just before it is
    yielded (either may be given; ``pace`` runs first). Both default OFF —
    ``delay_s=0.0`` / ``pace=None`` — so every existing test keeps its exact
    behaviour AND its exact timing. They exist so a turn can be genuinely
    mid-stream when ⏹ Stop arrives: the row A4.5 gate could otherwise only
    approximate that by blocking on an ask-tier permission chip. Keep any
    delay in the tens of milliseconds; the loop closes the generator on
    cancel, so a paced stream stops promptly rather than sleeping out its
    script.

    Attributes:
        calls: Every ``ChatRequest`` passed to ``stream()``, in order.
    """

    #: Registry id the eval runner keys on; the picker never lists it.
    id = "fake"
    #: Scripted thinking blocks play back, so the flag is truthful.
    supports_thinking = True

    def __init__(
        self,
        turns: list | Callable[[ChatRequest], list | dict],
        model: str = "fake-chat",
        delay_s: float = 0.0,
        pace: Callable[[ChatEvent], None] | None = None,
    ) -> None:
        self._turns = turns
        self._index = 0
        self._tool_counter = 0
        self._message_counter = 0
        self.model = model
        self.delay_s = delay_s
        self.pace = pace
        self.calls: list[ChatRequest] = []

    def stream(self, request: ChatRequest) -> Iterator[ChatEvent]:
        """Record the request and stream the next scripted turn.

        Raises:
            IndexError: (list mode) if the script is exhausted.
            TypeError: if ``turns`` was constructed with an unsupported type.
        """
        self.calls.append(request)
        turn = self._next_turn(request)
        return self._play(turn)

    def _next_turn(self, request: ChatRequest) -> list | dict:
        if callable(self._turns) and not isinstance(self._turns, (list, dict)):
            return self._turns(request)
        if isinstance(self._turns, list):
            turn = self._turns[self._index]
            self._index += 1
            return turn
        raise TypeError(f"FakeChatBackend: unsupported turns type {type(self._turns)}")

    def _play(self, turn: list | dict) -> Iterator[ChatEvent]:
        """The scripted events, paced. With ``pace``/``delay_s`` at their
        defaults this is a plain pass-through, so an unpaced backend streams
        exactly as it always did."""
        for event in self._events(turn):
            if self.pace is not None:
                self.pace(event)
            if self.delay_s:
                time.sleep(self.delay_s)
            yield event

    def _events(self, turn: list | dict) -> Iterator[ChatEvent]:
        if isinstance(turn, dict):
            raw_blocks = list(turn.get("content", []))
            stop_reason = turn.get("stop_reason")
            stop_details = turn.get("stop_details")
        else:
            raw_blocks = list(turn)
            stop_reason = None
            stop_details = None

        self._message_counter += 1
        yield MessageStart(model=self.model, message_id=f"msg_fake_{self._message_counter}")

        blocks: list[dict] = []
        for index, raw in enumerate(raw_blocks):
            block = dict(raw)
            kind = block.get("type")
            if kind == "text":
                text = block.get("text", "")
                mid = max(1, len(text) // 2)
                yield TextDelta(index=index, text=text[:mid])
                yield TextDelta(index=index, text=text[mid:])
            elif kind == "tool_use":
                if not block.get("id"):
                    self._tool_counter += 1
                    block["id"] = f"toolu_fake_{self._tool_counter}"
                block.setdefault("input", {})
                yield ToolUseStart(index=index, id=block["id"], name=block["name"])
                yield ToolInputDelta(index=index, id=block["id"], partial_json=json.dumps(block["input"]))
            elif kind == "thinking":
                yield ThinkingDelta(index=index, text=block.get("thinking", ""))
            yield ContentBlockDone(index=index, block=block)
            blocks.append(block)

        if stop_reason is None:
            stop_reason = "tool_use" if any(b.get("type") == "tool_use" for b in blocks) else "end_turn"
        yield MessageStop(stop_reason=stop_reason, usage=Usage(), content=blocks, stop_details=stop_details)
